config/routes.rb
Rails.application.routes.draw do
  get 'profiles/new'
  get 'profile/new'
  get 'sessions/new'
  root 'pages#index'
  get 'pages/help'
  get 'pages/link'
  resources :users
  resources :topics
  resources :profiles
  
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get '/comments/:topic_id/new', to: 'comments#new', as: 'comments'
  post '/comments/:topic_id/create', to: 'comments#create', as: 'comments_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/image_file.rb
class ImageFile < ApplicationRecord
  belongs_to :topics,optional: true
  mount_uploader :images, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, ImageUploader
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  belongs_to :user
  
  mount_uploader :image, ImageUploader
  
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments, dependent: :destroy
  has_many :image_files,dependent: :destroy
  accepts_nested_attributes_for :image_files,allow_destroy: true
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true,length:{maximum:15}
  validates :email,format:{with:/\A[\w\-.]+@[a-z]+.[a-z]+.[a-z]\z/}
  validates :password,format:{with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\z/}
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comments
  belongs_to :profile

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :user_logged_in?
  
  def new
    @topic = Topic.find_by(params[:topic_id]) #投稿画面に移行するときtopic_idは持ってこれないため、find_byでTopicモデルから探してインスタンス変数に入れて
    @comment = Comment.new
  end
  
  def create
     @comment = current_user.comments.new(comment_params) #@commentはcontent,user_id,topic_idを保存している
    if @comment.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
   private
  def comment_params
    params.require(:comment).permit(:content, :topic_id, :user_id)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :user_logged_in?
  
  def index
    @favorite_topics=current_user.favorite_topics
  end
  
  def create
    favorite = Favorite.new
    favorite.user_id=current_user.id
    favorite.topic_id=params[:topic_id]
    if favorite.save
      redirect_to topics_path, success:'お気に入りに登録しました'
    else
      redirect_to topics_path, danger:'お気に入りに登録に失敗しました'
    end
  end
  def destroy
    Favorite.find_by(topic_id: params[:topic_id],user_id: current_user.id).destroy
    flash[:success]="お気に入りを削除しました"
    redirect_to topics_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :forbid_login_user, {only: [:index]}

  def index
  end

  def help
  end
  
  def link
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def new
    @profile = Profile.new
  end
  
  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to user_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:photo, :hobby, :greeting).merge(user_id: current_user.id)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :forbid_login_user, {only: [:new]}
  #↑特定のViewをログイン時に表示させないようにするときbefore_actionで適応させるアクションをonlyで指定する。指定しないとコントローラー内全てに適応される。
  
  def new
  end

  def create
    user = User.find_by(email:session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to topics_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url,info:'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def session_params
    params.require(:session).permit(:email, :password)
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :user_logged_in?
  before_action :edit_restrict,{only:[:edit]}
  
  def index
    @topics = Topic.all.includes(:favorite_users)
    @topics = Topic.all.order(created_at: :desc) #新しい順に並べる。descは降順（逆から並べる。３、２、１、の順の様に）、created_atは作成日時。orderメソッドとは、データベースから取得してきた値を並び替えることができるメソッドです。
    
  end
  
  def new
    @topic = Topic.new
    @image_file = @topic.image_files.build
  end
  
  def edit
    
  end
  
  def update
    @topic = Topic.find(params[:id]) #編集したデータを受け取っている。
    @topic.update(topic_params) #受け取ったtopic_paramsのデータ（編集されたデータ）をDBに更新している。
    redirect_to topics_path #更新し終わったらtopicのindex.htmlへ
  end
  
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:description, image_files_attributes: [:images]).merge(user_id: current_user.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @users = User.new
  end
  
  def show
    @user = User.find_by(id: params[:id])
    @topics = @user.topics.order(created_at: :desc)
    @profile = @user.profile
  end
  #params[:id]は画面上で取得したidを入れている。よって、@userはparamsで取得したidをfind_byでUserモデルから取ってきたデータが入っている。
  #@profileは@userのidを使ってprofileモデルのデータを取ってきたいので、modelsでアソシエーション組んであれば、@user.profileの書き方でOK
  #アソシエーションくんでなければ、find_by(user_id: @user.id)で探してあげないと取ってこれない。

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success:'登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Comment</h1>
        <%= form_for @comment, url: comments_create_path do |f| %>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_area:content, class: 'form-control' %>
          <%= f.hidden_field:topic_id, :value => params[:topic_id] %>
        </div>
        <% if logged_in? %>
        <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= link_to comments_path(topic_id: topic.id), method: :get do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
            <p class="comment">コメント</p>
              <% topic.comments.each do |comment| %>
                <p class="topic-text">
                  <%= comment.content %>
                </p>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Topic Edit</h1>
        <%= form_for @topic  do |f| %>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area:description, class: 'form-control' %>
        </div>
        <% if logged_in? %>
          <%= f.submit '更新', class: 'btn btn-black btn-block' %> <%# submitは自動でupdateかcreateかを判断してくれる。formメソッドのおかげ %>
          <%= link_to "削除する", "/topics/#{@topic.id}", method: :delete %>
          <%# 削除する際のroutingはpathが指定されていなかったら、urlの指定（"/topics/#{@topic.id}"）で書かないとdestroyアクションを呼べない %>
          <%= link_to "戻る", topics_path %>
        <% end %>
        
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <div class="topic-time">
              <%= l topic.created_at, format: :long %>
              <%# lメソッドで日時を取得できるが、日本表記にするためgem 'i18n_generators'をインストールし、config/locales/jaymlの設定を使い回す。%>
            </div>
              <% topic.image_files.each do |file| %>
                <%= image_tag file.url %>
              <% end %>
              <%= image_tag topic.image.url %>
              <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <% end %>
              <% else %>
                 <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                   <i class="fa fa-heart" style="color:red" aria-hidden="true"></i>
                 <% end %>
                 <%= topic.favorite_users.count %>
              <% end %>
              <%= link_to comments_path(topic_id: topic.id), method: :get do %>
                <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
              <% end %>
              <% if topic.user == current_user %> <%# ログインしているユーザーとトピックのユーザーが同じであるかどうか %>
                <%= link_to edit_topic_path(id: topic.id), method: :get do %> <%# topic_id: topic.idだとエラーになってtopic.idだとedit.htmlにtopicのid渡してくれた　%>
                  <i class="fa fa-edit fa-lg" style="color:black"></i>
                <% end %>
              <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
            <p class="comment">コメント</p>
              <% topic.comments.each do |comment| %>
                <p class="topic-comment">
                  <%= link_to user_path(comment.user_id) do %>
                    <%= comment.user.name %>
                  <% end %><%# コメント投稿者の名前を表示させている %>
                  <%= comment.content %>
                </p>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.fields_for :image_files do |i| %>
              <%= i.label :image %>
              <%= i.file_field :image, multiple: true, name: "image_files[image][]" %>
            <% end %>
          </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area:description, class: 'form-control' %>
        </div>
        <% if logged_in? %>
        <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">User Edit</h1>
        <%= form_for @user  do |f| %>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.label :hobby %>
          <%= f.text_area:hobby, class: 'form-control' %>
        </div>
        <% if logged_in? %>
          <%= f.submit '更新', class: 'btn btn-black btn-block' %> <%# submitは自動でupdateかcreateかを判断してくれる。formメソッドのおかげ %>
          <%= link_to "削除する", "/user/#{@user.id}", method: :delete %>
          <%# 削除する際のroutingはpathが指定されていなかったら、urlの指定（"/topics/#{@topic.id}"）で書かないとdestroyアクションを呼べない %>
          <%= link_to "戻る", user_path %>
        <% end %>
        
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="topic-index-wrapper">
  <div class="user-profile">
    <% if @profile.nil? %>
      <%= image_tag 'icons/user-regular.svg', class: 'profile-image' %>
    <% else %>
      <%= image_tag @profile.photo.url, class: 'profile-image' %>
    <% end %>
    
    <div class="profile_tag">
          <% if @user == current_user%> <%# ログインしているユーザーとトピックのユーザーが同じであるかどうか %>
            <%= link_to new_profile_path, method: :get do %> <%#profileの作成へリンクさせる%>
              <i class="far fa-user-circle" style="color:black"></i>
            <% end %>
            <%#= link_to edit_profile_path(), method: :get do %> <%# profileの編集へリンクさせる　%>
              <i class="fa fa-edit fa-lg" style="color:black"></i>
            <%# end %>
          <% end %>
    </div>
      <p class ="profile-name">
        <h5><font color="#4169e1">Name</font></h5>
        <%= @user.name %>
        <%# この@userには、showメソッドの @user = User.find_by(id: params[:id])で、検索したidのUserモデルのデータが全て入っている。
        このidは、このページに飛ぶときに取得したidで検索している。よって@user.nameで、@user内のnameカラムのデータを呼んでいる。%>
      </p>
      <p class ="profile-hobby">
        <h5><font color="#4169e1">Hobby</font></h5>
        <% if @profile.nil? %>
          <%= "None" %>
        <% else %>
          <%= @profile.hobby %>
        <% end %>
        <%#= @profile.nil? ? "None" : @profile.hobby %>
      </p>
      <p class ="profile-greeting">
        <h5><font color="#4169e1">Greeting</font></h5>
        <% if @profile.nil? %>
          <%= "None" %>
        <% else %>
          <%= @profile.greeting %>
        <% end %>
      </p>
  </div>
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <div class="topic-time">
              <%= l topic.created_at, format: :long %>
              <%# lメソッドで日時を取得できるが、日本表記にするためgem 'i18n_generators'をインストールし、config/locales/jaymlの設定を使い回す。%>
            </div>
            <%= image_tag topic.image.url %>
              <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <% end %>
              <% else %>
                 <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                   <i class="fa fa-heart" style="color:red" aria-hidden="true"></i>
                 <% end %>
                 <%= topic.favorite_users.count %>
              <% end %>
              <%= link_to comments_path(topic_id: topic.id), method: :get do %>
                <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
              <% end %>
              <% if topic.user == current_user %> <%# ログインしているユーザーとトピックのユーザーが同じであるかどうか %>
                <%= link_to edit_topic_path(id: topic.id), method: :get do %> <%# topic_id: topic.idだとエラーになってtopic.idだとedit.htmlにtopicのid渡してくれた　%>
                  <i class="fa fa-edit fa-lg" style="color:black"></i>
                <% end %>
              <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
            <p class="comment">コメント</p>
              <% topic.comments.each do |comment| %>
                <p class="topic-comment">
                  <%= link_to user_path(comment.user_id) do %>
                    <%= comment.user.name %>
                  <% end %>
                  <%= comment.content %>
                </p>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>